spring.application.name=Melihs_Hotel

# 1. Die Datenbank-Verbindung (In-Memory)
spring.datasource.url=jdbc:h2:mem:hoteldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Hibernate / JPA Einstellungen
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Sagt Hibernate: "Lies meine @Entity Klassen und erstelle/update die Tabellen automatisch"
spring.jpa.hibernate.ddl-auto=update
# Zeigt dir in der Konsole an, welches SQL Hibernate generiert (super zum Debuggen!)
spring.jpa.show-sql=true

# 3. H2 Web-Konsole (Dein bester Freund in der Entwicklungsphase)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
